### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by softedco**
Optimized your code a bit, didn't remove anything important. Shortened the checks to a one liner so they are now moved to the fetch_url function. Open window related checks were removed because they are not needed.

### CODE REVIEW

**Comment by TrueFantom** [comment]
@softedco Thanks for the optimization!
I recently started programming on JS, so I'm glad you showed me how to make the code more structured)

**Comment by softedco** [comment]
You're welcome!

**Comment by True-Fantom** [comment]
@softedco

I edited the code a bit. Think in the `open window block` should be possible to specify a default value. I did it by adding a menu, but I think it's not very convenient.

**Comment by softedco** [comment]
I think the default value shouldn't be empty in the first place since you don't typically open a window with '' by '' resolution, it would make sense to set it to 480 and 360, for example.

**Comment by True-Fantom** [comment]
@softedco I mean default as for the browser. for example, my default windows open as 700 by 700.
Screenshot_179

**Pull request merged**
